### ISSUE TITLE
Cannot extend Component class

### ISSUE THREAD

**Issue by gmreburn** [lovetoys/preset#1]
I am receiving error "lib/lovetoys/lib/middleclass.lua:175: attempt to call method 'subclass' (a nil value)" when initializing any component which inherits from Component. The lovetoys readme suggests that you should not inherit from Component "Collection of functions for creating and working with Component classes. There is no Component class; As components are only 'data bags', you can just use standard middleclass classes to implement your components."

I am happy to submit a PR to change these components if you agree.

https://github.com/lovetoys/preset/blob/b3826d2744f73c2b758d9bbc4b58273b982f745a/src/components/physic/Transformable.lua#L3

Should be:

```
local Transformable = class("Transformable") 
```

**Comment by raffomania** [comment]
no need to create a PR, should be fixed now. thanks! :)
